config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do

    # mount_devise_token_auth_for 'User', at: 'auth'
    namespace :v1 do
      # resources :store_images, only:[:index, :show, :update] do
      get 'location', to: 'locations#index'
      # get 'image-stores', to: 'images#new'
      post 'locations', to: 'locations#create'
      get '/location/:id', to: 'locations#index'


    end

  end
  get '/locations', to:'locations#locations'
  get '/locations/new', to:'locations#new'
  post '/locations/new', to:'locations#create'
  post '/locations', to:'locations#create'
  get '/locations/show', to:'locations#show'
  get '/locations/:id/edit', to:'locations#edit_location'
  patch '/locations/:id', to:'locations#update', as: 'location'




  # get '/coord', to: 'locations#convert'


  # post '/locations/new', to:'images#create'
  #
     root 'homes#home'
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coordinate.rb
class Coordinate < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord

  def coordinates
    {
        lat:lat,
        long:long
    }
  end
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < ApplicationController
  skip_before_action :verify_authenticity_token



  def index
    render json: Location.all
  end
  def new
    @location= Location.new
  end

  def show
    @location = Location.find(params[id])
    render json: @location
  end

  def create
    @location = Location.new(location_store_params)
    @location.status = :requested

    if @location.save
      @data = {
          success: true,
          message: 'Ride successfully requested.'
          # render json: image_store, status: :created, location: api_post_path(image_store)

      }
    else
      @data = {
          error: true,
          message: location.errors.full_messages
          # render json: @post.errors, status: :unprocessable_entity

      }

    end
    render json: @data
  end

  def update
    Location.update(location_store_params)
    head :no_content
  end

  def destroy
    Location.destroy(location_store_params)
    head :no_content
  end

  def edit_location
    @locations = Location.find(params[:id])
  end



  private
    def location_store_params
      params.require(:location).permit(:street, :city,:state, :zip_code, :phone_number, :lat, :long, :name, :url, :category)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  require 'geokit'
  Geokit::Geocoders::GoogleGeocoder.api_key = 'AIzaSyBCQUignv1ORcvDq18Z_OAbsaL1bAZjJiA'


  def new
    @locations = Location.new
  end

  def show
    @location = Location.all
  end

  def create
    @locations = Location.new(location_store_params)
    if @locations.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit_location
    @locations = Location.find(params[:id])
  end

  def update_location
    @locations = Location.find(params[:id])

    if @locations.update(location_store_params)
      redirect_to @locations
    else
      render 'edit_location'
    end
  end

  def locations

  end

  def convert
    @coords = Geocoder.search('Paris')
    # @coords = coord.first
  end


  def destroy_location
    @locations = Location.find(params[:id])
    @locations.destroy

    redirect_to locations_path
    # redirect_to root_path
  end


  private

    def location_store_params
      params.require(:location).permit(:street, :city, :state, :zip_code, :phone_number, :lat, :long, :name, :url, :category)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories
    [
        ["none"],
        ['grocery'],
        ['restaurant']
    ]

  end
end

app/helpers/states_helper.rb
module StatesHelper

  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end

end

app/views/homes/home.html.erb
<p>Hello</p>
<%= link_to 'Create New Locations', locations_path, class: 'ui inverted violet button' %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="ui center aligned container ">
  <p class="MuiTypography-root MuiTypography-body2 MuiTypography-colorTextSecondary">
      Made with ❤️ by Bikram Subedi
    </p>
  </div>
</footer>

app/views/layouts/_top_nav_bar.html.erb
<div class="ui fixed inverted large secondary menu" style="background-color: #4a69bb;">
  <div class="ui container">
    <div class="header item" id="top-nav">
      <a class="<%= current_page?(root_path) ? "active" : '' %> item" href="<%= root_path %>">
                <h>Home</h>
      </a>
    </div>
<!--   -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NepaliApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.js"></script>

  </head>

  <body>
  <div class="ui container" id="main-content">

    <%= render 'layouts/top_nav_bar' %>
    <br/>
    <br/>
    <br/>
    <br/>
    <%= yield %>
  </div>
  </body>
  <br/>
  <br/>
  <br/>
  <br/>
  <%= render 'layouts/footer' %>
</html>

app/views/locations/_new_form.html.erb
<div class="middle">
  <h2>Add new Location</h2>
</div>

<div class="top_left">
  <%= link_to 'Go back to Dashboard', locations_path, class: 'ui inverted violet button' %>
</div>

<form class="ui form" <%= form_for @locations, html: {multipart: true} do |form| %>

  <div class="ui very centered raised text container segment">
    <a class="ui teal ribbon label">Contact</a><br/><br/>

    <!--  <form class="ui form" <%#= form_for @locations, html: {multipart: true} do |form| %>-->
    <div class="two fields">
      <div class="five wide required field">
        <%= form.label :name_of_store %>
        <%= form.text_field :name, autocomplete: "off", require: false, autofocus: true %>
      </div>
      <div class="four wide required field ">
        <%= form.label :phone_number %>
        <%= form.phone_field :phone_number, autocomplete: "off", require: false, autofocus: true %>
      </div>
    </div>
    <div class="four wide required field ">
      <%= form.label :category %>
      <%= form.select :category, options_for_select(categories), class: 'ui fluid search selection dropdown', required: true %>
    </div>
    <%#end %>
    <!--  </form>-->
  </div>
  <!--<div class="ui very centered padded text container segment">-->
  <!--  <div class="ui raised segment">-->
  <div class="ui very centered raised text container segment">
    <a class="ui teal ribbon label">Location info</a><br/><br/>

    <!--    <form class="ui form" <%#= form_for @locations, html: {multipart: true} do |form| %>-->
    <!--      <div class="five wide required field" >-->
    <%#= form.label :name_of_store %>
    <%#= form.text_field :name, autocomplete: "off", require: false, autofocus: true %>
    <!--      </div>-->
    <div class="eight wide required field ">
      <%= form.label :street_Address %>
      <%= form.text_field :street, autocomplete: "off", require: false, autofocus: true %>
    </div>

    <div class="four fields">
      <div class="three wide required field ">
        <%= form.label :Zip_code %>
        <%= form.text_field :zip_code, autocomplete: "off", require: false, autofocus: true %>
      </div>
      <div class="six wide required field ">
        <%= form.label :City %>
        <%= form.text_field :city, autocomplete: "off", require: false, autofocus: true %>
      </div>
      <!--      <div class="inline field ">-->
      <%#= form.label :phone_number %>
      <%#= form.phone_field :phone_number, autocomplete: "off", require: false, autofocus: true %>
      <!--      </div>-->
    </div>
    <!--      <div class="two fields">-->
    <!--        <div class="three wide required field ">-->
    <%#= form.label :latitude%>
    <%#= form.text_field :lat, autocomplete: "off", require: false, autofocus: true %>
    <!--        </div>-->
    <!--        <div class="three wide required field ">-->
    <%#= form.label :longitude %>
    <%#= form.text_field :long, autocomplete: "off", require: false, autofocus: true %>
    <!--        </div>-->
    <!--      </div>-->
    <div class="five wide required field ">
      <%= form.label :State %>
      <%= form.select :state, options_for_select(us_states), class: 'ui fluid search selection dropdown', required: true %>
      <!--      <select class="ui fluid search dropdown" multiple="">-->
      <!--        <option value="">State</option>-->
      <!--        <option value="AL">Alabama</option>-->
      <!--        <option value="AK">Alaska</option>-->
      <!--        <option value="AZ">Arizona</option>-->
      <!--        <option value="AR">Arkansas</option>-->
      <!--        <option value="CA">California</option>-->
      <!--        <option value="CO">Colorado</option>-->
      <!--        <option value="CT">Connecticut</option>-->
      <!--        <option value="DE">Delaware</option>-->
      <!--        <option value="DC">District Of Columbia</option>-->
      <!--        <option value="FL">Florida</option>-->
      <!--        <option value="GA">Georgia</option>-->
      <!--        <option value="HI">Hawaii</option>-->
      <!--        <option value="ID">Idaho</option>-->
      <!--        <option value="IL">Illinois</option>-->
      <!--        <option value="IN">Indiana</option>-->
      <!--        <option value="IA">Iowa</option>-->
      <!--        <option value="KS">Kansas</option>-->
      <!--        <option value="KY">Kentucky</option>-->
      <!--        <option value="LA">Louisiana</option>-->
      <!--        <option value="ME">Maine</option>-->
      <!--        <option value="MD">Maryland</option>-->
      <!--        <option value="MA">Massachusetts</option>-->
      <!--        <option value="MI">Michigan</option>-->
      <!--        <option value="MN">Minnesota</option>-->
      <!--        <option value="MS">Mississippi</option>-->
      <!--        <option value="MO">Missouri</option>-->
      <!--        <option value="MT">Montana</option>-->
      <!--        <option value="NE">Nebraska</option>-->
      <!--        <option value="NV">Nevada</option>-->
      <!--        <option value="NH">New Hampshire</option>-->
      <!--        <option value="NJ">New Jersey</option>-->
      <!--        <option value="NM">New Mexico</option>-->
      <!--        <option value="NY">New York</option>-->
      <!--        <option value="NC">North Carolina</option>-->
      <!--        <option value="ND">North Dakota</option>-->
      <!--        <option value="OH">Ohio</option>-->
      <!--        <option value="OK">Oklahoma</option>-->
      <!--        <option value="OR">Oregon</option>-->
      <!--        <option value="PA">Pennsylvania</option>-->
      <!--        <option value="RI">Rhode Island</option>-->
      <!--        <option value="SC">South Carolina</option>-->
      <!--        <option value="SD">South Dakota</option>-->
      <!--        <option value="TN">Tennessee</option>-->
      <!--        <option value="TX">Texas</option>-->
      <!--        <option value="UT">Utah</option>-->
      <!--        <option value="VT">Vermont</option>-->
      <!--        <option value="VA">Virginia</option>-->
      <!--        <option value="WA">Washington</option>-->
      <!--        <option value="WV">West Virginia</option>-->
      <!--        <option value="WI">Wisconsin</option>-->
      <!--        <option value="WY">Wyoming</option>-->
      <!--      </select>-->

    </div>
    <br/>


    <!--    <div class="actions" id="center-button" style="padding-left: 300px">-->
    <%#= form.submit "save", class: 'ui primary button' %>
    <!--    </div>-->

    <%# end %>
    <!--  </form>-->
  </div>

  <div class="ui very centered raised text container segment">
    <a class="ui teal ribbon label">Coordinates</a><br/><br/>

    <!--  <form class="ui form" <%#= form_for @locations, html: {multipart: true} do |form| %>-->
    <div class="two fields">
      <div class="three wide required field ">
        <%= form.label :latitude %>
        <%= form.text_field :lat, autocomplete: "off", require: false, autofocus: true %>
      </div>
      <div class="three wide required field ">
        <%= form.label :longitude %>
        <%= form.text_field :long, autocomplete: "off", require: false, autofocus: true %>
      </div>
    </div>

<%#end %>
    <!--  </form>-->
  </div>

  <div class="ui very centered raised text container segment">
    <a class="ui teal ribbon label">Image or link</a><br/><br/>
    <!--  <form class="ui form" <%#= form_for @locations, html: {multipart: true} do |form| %>-->
    <div class="nine wide required field ">
      <%= form.label :image_or_link %>
      <%= form.text_field :url, autocomplete: "off", require: false, autofocus: true %>
    </div>
    <%#end %>
    <!--  </form>-->
  </div>
  <div class="actions" id="center-button" style="padding-left: 220px">
    <%= form.submit "create store", class: 'ui primary button' %>
  </div>
  <br/>
  <br/>
<% end %>
</form>




<script>
    $('.ui.dropdown')
        .dropdown();

</script>

app/views/locations/convert.html.erb
<%@coords.each do |co| %>
  <p><%=co.first.coordinates %><p/>

<% end %>

app/views/locations/edit_location.html.erb
<%=render 'new_form' %>

app/views/locations/locations.html.erb
<h2>Locations</h2>

  <%= link_to 'Create New Locations', locations_new_path, class: 'ui inverted violet button' %>

app/views/locations/new.html.erb
<%= render 'new_form' %>

app/views/locations/show.html.erb
<div class="ui grid">
  <%#= render 'users/right_menu' %>
  <div class="fourteen wide column">
    <h1>Dashboard</h1>
    <div>
      <div class="ui stackable four cards">
        <% @location.each do |loc| %>
          <div class="ui card">
            <div class="content">
              <div class="header">
                <%= loc[:name] %>
              </div>
              <div class="ui vertical segments">
                <div class="ui segment">
                  <div class="ui small images">
                  </div>
                  <img src="<%= loc[:url] %>" width="175" height="130">

                </div>
              </div>
            </div>
            <!--            <div class="extra content">-->
            <div class="content">
              <p>Address:   <%= loc[:street] %> <%= loc[:city] %>, <%= loc[:state] %> <%= loc[:zip_code] %></p>
              <p>Phone Number: <%= loc[:phone_number] %></p>
              <h5>Type: <%= loc[:category] %></h5>

            </div>
            <div>
              <td><%= link_to 'Edit', edit_location_path(loc), class: 'ui primary button' %></td>
              <td><%= link_to 'delete', locations_path(loc), class: 'ui primary button' %></td>
            </div>

          </div>

        <% end %>
      </div>
    </div>
    <br/>
    <%= link_to 'Add new address', new_location_path, class: 'ui inverted violet button' %>
  </div>
</div>